-- ==========================================
-- ABSENSI.PRO DATABASE SCHEMA
-- ==========================================

-- 1. Profiles Table (Student Data)
CREATE TABLE profiles (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  npm TEXT UNIQUE NOT NULL,
  full_name TEXT NOT NULL,
  home_lat DOUBLE PRECISION NOT NULL,
  home_long DOUBLE PRECISION NOT NULL,
  provinsi TEXT,
  kabupaten TEXT,
  kecamatan TEXT,
  kelurahan TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Attendance Logs Table
CREATE TABLE attendance_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  npm TEXT REFERENCES profiles(npm) ON DELETE CASCADE,
  status TEXT NOT NULL, -- 'In-range' or 'Out-range'
  photo_url TEXT,
  reason TEXT,
  timestamp TIMESTAMPTZ DEFAULT NOW(),
  lat DOUBLE PRECISION,
  long DOUBLE PRECISION
);

-- 3. Storage Setup (Bucket for Photos)
-- Run this in SQL Editor to create the bucket
INSERT INTO storage.buckets (id, name, public)
VALUES ('attendance-photos', 'attendance-photos', true)
ON CONFLICT (id) DO NOTHING;

-- 4. Enable Row Level Security (RLS)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendance_logs ENABLE ROW LEVEL SECURITY;

-- 5. Open Public Access Policies
CREATE POLICY "Public Profile Access" ON profiles FOR ALL USING (true);
CREATE POLICY "Public Logs Access" ON attendance_logs FOR ALL USING (true);
CREATE POLICY "Public Storage Upload" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'attendance-photos');
CREATE POLICY "Public Storage View" ON storage.objects FOR SELECT USING (bucket_id = 'attendance-photos');
